# >>> ALGORITHM PUZZLES <<<

# Question 1 - Even Odd Classifier

# Problems were generated by AI; solutions are my own work.
# https://github.com/cetin172004/AlgorithmPuzzles
# cetin172004

# ==============================================================================

# Problem Description:
# Prompt the user to enter up to 10 integers, or exit early by entering 'q'.
# Once 10 valid integers have been entered, classify them into even and odd numbers.
# Then, display the contents and lengths of both even and odd lists.
# Repeat the process until the user decides to quit.
#
# Example:
# Input: 1, 4, 7, 2, 6, 3, 9, 8, 10, 5
# Output (formatted for clarity in the console):
#     Odd Numbers: [1, 7, 3, 9, 5] (count: 5)
#     Even Numbers: [4, 2, 6, 8, 10] (count: 5)

# ==============================================================================

print("Welcome to the program!\n")

user_numbers = []
counter = 1
list_completed = False
odd_numbers = []
even_numbers = []

while True:
    user_input = input(f"Please enter integer #{counter} (q to quit): ")

    if user_input.lower() == 'q':
        print("Goodbye!")
        break

    try:
        number = int(user_input)
        user_numbers.append(number)
        counter += 1

        if counter > 10:
            list_completed = True

    except ValueError: # catch only invalid integer conversion errors
		#  just except: is syntactically valid, but it catches all exceptions (not safe)
        print("Invalid input. Please enter a valid integer.")

    if list_completed:
        # separate numbers
        odd_numbers = [n for n in user_numbers if n % 2 != 0] # list comprehension
        even_numbers = [n for n in user_numbers if n % 2 == 0]

        # display results
        print(f"""
*=================================================================*
	Odd Numbers: {odd_numbers}
	Count of Odd Numbers: {len(odd_numbers)}
*-----------------------------------------------------------------*
	Even Numbers: {even_numbers}
	Count of Even Numbers: {len(even_numbers)}
*=================================================================*
""")

        # reset values
        user_numbers.clear()
        counter = 1
        list_completed = False
        odd_numbers.clear()
        even_numbers.clear()
